[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "SMaRT-Pack"
version = "0.1.0"
description = "A package containing the workflow for a machine learning internship part of the SMaRT 2026 Internship"
authors = [
  { name = "Simon Matei", email = "simonsamuelmatei2007@gmail.com" }
]
license = "MIT"
license-files = ["LICEN[CS]E*"]
readme = "README.md"
requires-python = ">=3.10"
keywords = ["workflow","machine-learning","data-science","SMaRT 2026"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
]
dependencies = [
    "pandas >= 3.0.0",
    "numpy >= 2.0.0",
    "scikit-learn >= 1.8.0",
]

[project.urls]
Homepage = "https://github.com/SimonSMatei/SMaRT-Pack"
Issues = "https://github.com/SimonSMatei/SMaRT-Pack/issues"